### PR TITLE
jdk9 port of UMLGraph

### PR DESCRIPTION
**Pull request by laurentschoelens**
Hi everyone, this is a first-step migration to jdk9 support (since new api used, the old jdk8 support as been dropped)
It generates UMLGraph based on classes.
Tested against jdk9 / jdk11 / jdk14 / jdk17.

Feel free to look at and use it

### CODE REVIEW

**Review by dspinellis — COMMENTED** [review]
This is a very big and badly needed pull request; thanks! I don't have time to review it exhaustively, but you appear to be going in the right direction, so I'll merge it.

**Comment by laurentschoelens** [comment]
@dspinellis : thanks for your answer,
I think there is still improvments to be done on this but it works well on the project itself.
Some options had name changes also, be careful.
May be this needed to be documented

**Comment by laurentschoelens** [comment]
This is based on these docs I found :
https://docs.oracle.com/en/java/javase/17/docs/api/jdk.javadoc/jdk/javadoc/doclet/package-summary.html
https://openjdk.org/groups/compiler/using-new-doclet.html

**Comment by laurentschoelens** [comment]
Yes. Parsing option by command line and maven build due to new Doclet.Option API and parsing. Some have been double dashed to allow --myoption="something"

**Comment by dspinellis** [comment]
Oh, I see.  It would be great if you could update the documentation! A `git grep -e` should help you locate where the changed options are mentioned.  The documentation files are unfortunately in an extended version of XML/HTML, which I convert to plain HTML with a Perl script that's unfit for distribution.  I'll update them locally when you ping me.

Also, when I announce this, is there a Twitter or Mastodon handle you'd like me to use to refer to you?

**Pull request merged**
